In [1]:
import pandas as pd

file_path = "../data/raw/DOB_ECB_Violations_20260913 (1).csv"

df = pd.read_csv(file_path)

print("Dataset loaded:", df.shape)

Dataset loaded: (102467, 46)

C:\Users\gimha_9pk7du7\AppData\Local\Temp\ipykernel_20640\3580953808.py:5: DtypeWarning: Columns (28: SECTION_LAW_DESCRIPTION3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [2]:
for i, col in enumerate(df.columns, start=1):
    print(f"{i:2}. {col}")

 1. ISN_DOB_BIS_EXTRACT
 2. ECB_VIOLATION_NUMBER
 3. ECB_VIOLATION_STATUS
 4. DOB_VIOLATION_NUMBER
 5. BIN
 6. BORO
 7. BLOCK
 8. LOT
 9. HEARING_DATE
10. HEARING_TIME
11. SERVED_DATE
12. ISSUE_DATE
13. SEVERITY
14. VIOLATION_TYPE
15. RESPONDENT_NAME
16. RESPONDENT_HOUSE_NUMBER
17. RESPONDENT_STREET
18. RESPONDENT_CITY
19. RESPONDENT_ZIP
20. VIOLATION_DESCRIPTION
21. PENALITY_IMPOSED
22. AMOUNT_PAID
23. BALANCE_DUE
24. INFRACTION_CODE1
25. SECTION_LAW_DESCRIPTION1
26. INFRACTION_CODE2
27. SECTION_LAW_DESCRIPTION2
28. INFRACTION_CODE3
29. SECTION_LAW_DESCRIPTION3
30. INFRACTION_CODE4
31. SECTION_LAW_DESCRIPTION4
32. INFRACTION_CODE5
33. SECTION_LAW_DESCRIPTION5
34. INFRACTION_CODE6
35. SECTION_LAW_DESCRIPTION6
36. INFRACTION_CODE7
37. SECTION_LAW_DESCRIPTION7
38. INFRACTION_CODE8
39. SECTION_LAW_DESCRIPTION8
40. INFRACTION_CODE9
41. SECTION_LAW_DESCRIPTION9
42. INFRACTION_CODE10
43. SECTION_LAW_DESCRIPTION10
44. AGGRAVATED_LEVEL
45. HEARING_STATUS
46. CERTIFICATION_STATUS

In [3]:
id_columns = [
    "ISN_DOB_BIS_EXTRACT",
    "ECB_VIOLATION_NUMBER",
    "DOB_VIOLATION_NUMBER",
    "BIN",
    "BLOCK",
    "LOT"
]

for col in id_columns:
    print("\n" + "=" * 60)
    print(col)
    print("Data type:", df[col].dtype)
    print("Total records:", len(df))
    print("Non-null:", df[col].notna().sum())
    print("Unique:", df[col].nunique(dropna=True))
    print("Missing:", df[col].isna().sum())

============================================================
ISN_DOB_BIS_EXTRACT
Data type: int64
Total records: 102467
Non-null: 102467
Unique: 102467
Missing: 0

============================================================
ECB_VIOLATION_NUMBER
Data type: str
Total records: 102467
Non-null: 102467
Unique: 102467
Missing: 0

============================================================
DOB_VIOLATION_NUMBER
Data type: str
Total records: 102467
Non-null: 21654
Unique: 19986
Missing: 80813

============================================================
BIN
Data type: float64
Total records: 102467
Non-null: 102372
Unique: 38743
Missing: 95

============================================================
BLOCK
Data type: float64
Total records: 102467
Non-null: 101980
Unique: 9887
Missing: 487

============================================================
LOT
Data type: float64
Total records: 102467
Non-null: 101980
Unique: 643
Missing: 487

In [4]:
print("Unique BINs:", df["BIN"].nunique())
print("Total violations:", len(df))

bin_counts = df["BIN"].value_counts()

print("\nViolations per BIN:")
print(bin_counts.describe())

Unique BINs: 38743
Total violations: 102467

Violations per BIN:
count    38743.000000
mean         2.642335
std          2.955160
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         61.000000
Name: count, dtype: float64

In [5]:
print("\nTop 10 BINs by number of violations:")
print(bin_counts.head(10))

Top 10 BINs by number of violations:
BIN
3121398.0    61
4542690.0    44
3000000.0    43
3077911.0    42
4625285.0    41
4467715.0    41
2002977.0    40
3853823.0    39
2018266.0    39
1038561.0    39
Name: count, dtype: int64

In [6]:
print(
    "ECB_VIOLATION_NUMBER unique:",
    df["ECB_VIOLATION_NUMBER"].nunique()
)

print(
    "ECB_VIOLATION_NUMBER missing:",
    df["ECB_VIOLATION_NUMBER"].isna().sum()
)

print(
    "Is every ECB violation number unique?",
    df["ECB_VIOLATION_NUMBER"].is_unique
)

ECB_VIOLATION_NUMBER unique: 102467
ECB_VIOLATION_NUMBER missing: 0
Is every ECB violation number unique? True

In [7]:
print(df["AGGRAVATED_LEVEL"].value_counts(dropna=False))

AGGRAVATED_LEVEL
NO                            94199
AGGRAVATED OFFENSE LEVEL 1     7323
AGGRAVATED OFFENSE LEVEL 2      945
Name: count, dtype: int64

In [8]:
pd.crosstab(
    df["AGGRAVATED_LEVEL"],
    df["SEVERITY"],
    margins=True
)

SEVERITY                    CLASS - 1  CLASS - 2  CLASS - 3     All
AGGRAVATED_LEVEL
AGGRAVATED OFFENSE LEVEL 1       3066       4206         51    7323
AGGRAVATED OFFENSE LEVEL 2        777        165          3     945
NO                              36830      53236       4133   94199
All                             40673      57607       4187  102467

In [9]:
financial_columns = [
    "PENALITY_IMPOSED",
    "AMOUNT_PAID",
    "BALANCE_DUE"
]

for col in financial_columns:
    print("\n" + "=" * 60)
    print(col)
    print("Data type:", df[col].dtype)
    print("Missing:", df[col].isna().sum())
    print("Unique:", df[col].nunique())
    print("\nSample values:")
    print(df[col].value_counts(dropna=False).head(20))

============================================================
PENALITY_IMPOSED
Data type: str
Missing: 0
Unique: 98

Sample values:
PENALITY_IMPOSED
1,250     21300
2,500     17661
0         13366
6,250      8111
3,125      5517
5,000      5396
625        4554
12,500     4177
10,000     3277
1,280      3048
2,530      2479
500        2080
25,000     1746
2,400      1335
1,000      1135
1,600       685
1,562       596
250         591
800         582
5,030       500
Name: count, dtype: int64

============================================================
AMOUNT_PAID
Data type: str
Missing: 0
Unique: 1286

Sample values:
AMOUNT_PAID
0         83657
1,250      4044
2,500      3287
625        1385
1,280       815
5,000       792
620         532
2,530       475
500         393
1,000       358
2,400       303
250         287
800         276
1,600       252
10,000      205
655         149
6,250       143
312         130
3,125       120
310          99
Name: count, dtype: int64

============================================================
BALANCE_DUE
Data type: str
Missing: 0
Unique: 380

Sample values:
BALANCE_DUE
0         39296
2,500     13375
1,250     12445
6,250      7441
5,000      4283
12,500     4028
10,000     2862
3,125      2219
1,280      2216
625        2022
2,530      1993
25,000     1711
500        1538
2,400       929
1,000       701
5,030       416
1,600       392
250         305
6,280       245
800         242
Name: count, dtype: int64

In [10]:
financial_columns = [
    "PENALITY_IMPOSED",
    "AMOUNT_PAID",
    "BALANCE_DUE"
]

for col in financial_columns:
    print("\n" + "=" * 60)
    print(col)
    print("Data type:", df[col].dtype)
    print("Missing:", df[col].isna().sum())
    print("Unique:", df[col].nunique())
    print("First 10 values:")
    print(df[col].dropna().head(10).tolist())
    print("Last 10 values:")
    print(df[col].dropna().tail(10).tolist())

============================================================
PENALITY_IMPOSED
Data type: str
Missing: 0
Unique: 98
First 10 values:
['1,250', '6,250', '2,530', '1,250', '2,500', '4,800', '5,000', '2,500', '2,530', '1,250']
Last 10 values:
['2,500', '5,000', '1,250', '6,250', '6,250', '1,000', '1,250', '1,250', '3,125', '12,500']

============================================================
AMOUNT_PAID
Data type: str
Missing: 0
Unique: 1286
First 10 values:
['0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
Last 10 values:
['0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

============================================================
BALANCE_DUE
Data type: str
Missing: 0
Unique: 380
First 10 values:
['1,250', '6,250', '2,530', '1,250', '2,500', '4,800', '5,000', '2,500', '2,530', '1,250']
Last 10 values:
['2,500', '5,000', '1,250', '6,250', '6,250', '1,000', '1,250', '1,250', '3,125', '12,500']

In [11]:
for col in financial_columns:
    cleaned = (
        df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    numeric = pd.to_numeric(cleaned, errors="coerce")

    print("\n" + "=" * 60)
    print(col)
    print("Could convert to numeric:", numeric.notna().sum())
    print("Could NOT convert:", numeric.isna().sum())

    if numeric.notna().any():
        print("Minimum:", numeric.min())
        print("Maximum:", numeric.max())

============================================================
PENALITY_IMPOSED
Could convert to numeric: 102467
Could NOT convert: 0
Minimum: 0
Maximum: 70000

============================================================
AMOUNT_PAID
Could convert to numeric: 102467
Could NOT convert: 0
Minimum: 0
Maximum: 57500

============================================================
BALANCE_DUE
Could convert to numeric: 102467
Could NOT convert: 0
Minimum: -35000
Maximum: 70000

In [12]:
negative_balance = df[
    pd.to_numeric(
        df["BALANCE_DUE"].astype(str).str.replace(",", "", regex=False),
        errors="coerce"
    ) < 0
]

print("Negative BALANCE_DUE records:", len(negative_balance))

print(
    negative_balance[
        [
            "BALANCE_DUE",
            "AMOUNT_PAID",
            "PENALITY_IMPOSED",
            "SEVERITY",
            "ECB_VIOLATION_STATUS"
        ]
    ].head(20)
)

Negative BALANCE_DUE records: 408
     BALANCE_DUE AMOUNT_PAID PENALITY_IMPOSED   SEVERITY ECB_VIOLATION_STATUS
455          -60         680              620  CLASS - 2               ACTIVE
666       -1,280       2,560            1,280  CLASS - 2               ACTIVE
909         -620         620                0  CLASS - 2              RESOLVE
997       -1,250       1,250                0  CLASS - 2              RESOLVE
1120      -3,125       6,604            3,125  CLASS - 2              RESOLVE
1131        -120         120                0  CLASS - 3              RESOLVE
1393      -1,250       1,250                0  CLASS - 2              RESOLVE
1501        -620         620                0  CLASS - 2              RESOLVE
1537      -5,000      10,165            5,000  CLASS - 2              RESOLVE
1880      -3,125       1,280            3,125  CLASS - 2              RESOLVE
2650        -620         620                0  CLASS - 2              RESOLVE
2716        -345       1,000              655  CLASS - 2               ACTIVE
2847      -6,250      12,712            6,250  CLASS - 1              RESOLVE
2848      -1,562       3,272            1,562  CLASS - 2              RESOLVE
2893      -3,125       6,250            3,125  CLASS - 2              RESOLVE
3367      -1,250       1,250                0  CLASS - 2              RESOLVE
3810      -5,000      10,485            5,000  CLASS - 2              RESOLVE
4151         -15       1,283            1,250  CLASS - 2               ACTIVE
4216         -30       5,030            5,000  CLASS - 1              RESOLVE
4243        -313         625              312  CLASS - 2              RESOLVE

In [13]:
balance_numeric = pd.to_numeric(
    df["BALANCE_DUE"].astype(str).str.replace(",", "", regex=False),
    errors="coerce"
)

print(balance_numeric.value_counts().sort_index().head(20))

BALANCE_DUE
-35000     1
-30188     1
-15975     1
-12709     1
-12500     3
-10000     1
-7500      1
-6454      1
-6453      1
-6250      6
-5083      1
-5000     22
-4970      2
-3875      1
-3750      1
-3650      1
-3500      1
-3161      1
-3125     46
-3025      1
Name: count, dtype: int64

In [14]:
date_columns = [
    "ISSUE_DATE",
    "SERVED_DATE",
    "HEARING_DATE"
]

for col in date_columns:
    print("\n" + "=" * 60)
    print(col)

    print("Data type:", df[col].dtype)
    print("Missing:", df[col].isna().sum())
    print("Unique:", df[col].nunique())

    print("Minimum:", df[col].min())
    print("Maximum:", df[col].max())

    print("Most common:")
    print(df[col].value_counts(dropna=False).head(10))

============================================================
ISSUE_DATE
Data type: int64
Missing: 0
Unique: 618
Minimum: 20250101
Maximum: 20260910
Most common:
ISSUE_DATE
20250408    985
20250225    956
20250701    861
20260420    726
20250129    565
20250211    453
20250528    424
20250108    404
20260302    350
20260730    343
Name: count, dtype: int64

============================================================
SERVED_DATE
Data type: int64
Missing: 0
Unique: 619
Minimum: 0
Maximum: 20260910
Most common:
SERVED_DATE
20260604    396
20250424    375
20260507    371
20260521    371
20250807    370
20250501    370
20250717    368
20260601    367
20260512    365
20250731    362
Name: count, dtype: int64

============================================================
HEARING_DATE
Data type: int64
Missing: 0
Unique: 568
Minimum: 20250206
Maximum: 20271222
Most common:
HEARING_DATE
20261007    815
20261016    756
20261110    755
20261014    658
20261002    648
20260807    643
20261030    617
20260715    616
20261104    615
20261028    593
Name: count, dtype: int64

In [15]:
for col in date_columns:
    print(
        col,
        "zero values:",
        (df[col] == 0).sum()
    )

ISSUE_DATE zero values: 0
SERVED_DATE zero values: 7
HEARING_DATE zero values: 0

In [16]:
print("SERVED before ISSUE:",
      (df["SERVED_DATE"] < df["ISSUE_DATE"]).sum())

print("HEARING before ISSUE:",
      (df["HEARING_DATE"] < df["ISSUE_DATE"]).sum())

print("HEARING before SERVED:",
      (df["HEARING_DATE"] < df["SERVED_DATE"]).sum())

SERVED before ISSUE: 7
HEARING before ISSUE: 0
HEARING before SERVED: 0

# Feature Investigation and Selection

## Prediction Target

Target variable: `SEVERITY`

The model will predict:

- CLASS - 1
- CLASS - 2
- CLASS - 3

## Prediction Point

The intended prediction point is the violation/issue stage.

Therefore, features that are only generated after the violation progresses must be investigated for potential data leakage.

In [17]:
feature_decisions = pd.DataFrame({
    "Column": df.columns,
    "Role": "",
    "Decision": "",
    "Reason": "",
    "Preprocessing": ""
})

feature_decisions

                       Column Role Decision Reason Preprocessing
0         ISN_DOB_BIS_EXTRACT
1        ECB_VIOLATION_NUMBER
2        ECB_VIOLATION_STATUS
3        DOB_VIOLATION_NUMBER
4                         BIN
5                        BORO
6                       BLOCK
7                         LOT
8                HEARING_DATE
9                HEARING_TIME
10                SERVED_DATE
11                 ISSUE_DATE
12                   SEVERITY
13             VIOLATION_TYPE
14            RESPONDENT_NAME
15    RESPONDENT_HOUSE_NUMBER
16          RESPONDENT_STREET
17            RESPONDENT_CITY
18             RESPONDENT_ZIP
19      VIOLATION_DESCRIPTION
20           PENALITY_IMPOSED
21                AMOUNT_PAID
22                BALANCE_DUE
23           INFRACTION_CODE1
24   SECTION_LAW_DESCRIPTION1
25           INFRACTION_CODE2
26   SECTION_LAW_DESCRIPTION2
27           INFRACTION_CODE3
28   SECTION_LAW_DESCRIPTION3
29           INFRACTION_CODE4
30   SECTION_LAW_DESCRIPTION4
31           INFRACTION_CODE5
32   SECTION_LAW_DESCRIPTION5
33           INFRACTION_CODE6
34   SECTION_LAW_DESCRIPTION6
35           INFRACTION_CODE7
36   SECTION_LAW_DESCRIPTION7
37           INFRACTION_CODE8
38   SECTION_LAW_DESCRIPTION8
39           INFRACTION_CODE9
40   SECTION_LAW_DESCRIPTION9
41          INFRACTION_CODE10
42  SECTION_LAW_DESCRIPTION10
43           AGGRAVATED_LEVEL
44             HEARING_STATUS
45       CERTIFICATION_STATUS

In [18]:
decisions = {
    "ISN_DOB_BIS_EXTRACT": (
        "Identifier",
        "Remove",
        "Unique value for every record; no predictive meaning",
        "Drop"
    ),

    "ECB_VIOLATION_NUMBER": (
        "Identifier",
        "Remove",
        "Unique violation identifier for every record",
        "Drop"
    ),

    "SEVERITY": (
        "Target",
        "Target",
        "Three-class prediction target",
        "Encode target"
    ),

    "VIOLATION_TYPE": (
        "Feature",
        "Investigate/Keep",
        "12 violation categories may contain predictive information",
        "Categorical encoding"
    ),

    "BORO": (
        "Feature",
        "Investigate/Keep",
        "Geographical information with 5 categories",
        "Categorical encoding"
    ),

    "BIN": (
        "Feature",
        "Investigate/Keep",
        "Building identifier; repeated buildings allow historical feature engineering",
        "Historical feature engineering / categorical handling"
    ),

    "BLOCK": (
        "Feature",
        "Investigate/Keep",
        "Location identifier",
        "Categorical/location handling"
    ),

    "LOT": (
        "Feature",
        "Investigate/Keep",
        "Location identifier",
        "Categorical/location handling"
    ),

    "ISSUE_DATE": (
        "Feature",
        "Keep",
        "Available at the issue stage and contains temporal information",
        "Datetime conversion + feature engineering"
    ),

    "AGGRAVATED_LEVEL": (
        "Feature",
        "Investigate",
        "Strong relationship with SEVERITY; need to confirm when this value is assigned",
        "Categorical encoding if retained"
    ),

    "PENALITY_IMPOSED": (
        "Feature",
        "Investigate",
        "Monetary variable stored as formatted text; prediction-time availability must be confirmed",
        "String-to-numeric conversion if retained"
    ),

    "AMOUNT_PAID": (
        "Potential leakage",
        "Investigate",
        "Payment may occur after the prediction point",
        "String-to-numeric if retained"
    ),

    "BALANCE_DUE": (
        "Potential leakage",
        "Investigate",
        "Financial status may be generated after the prediction point",
        "String-to-numeric + investigate negative values"
    ),

    "HEARING_DATE": (
        "Potential leakage",
        "Investigate",
        "Hearing occurs later in the violation process",
        "Datetime conversion only if legitimately available"
    ),

    "HEARING_STATUS": (
        "Potential leakage",
        "Investigate",
        "Status may be determined after the initial violation",
        "Categorical encoding if retained"
    ),

    "CERTIFICATION_STATUS": (
        "Potential leakage",
        "Investigate",
        "May represent a later stage of the violation process",
        "Categorical encoding if retained"
    ),

    "ECB_VIOLATION_STATUS": (
        "Potential leakage",
        "Investigate",
        "Status may change as the violation progresses",
        "Categorical encoding if retained"
    ),

    "DOB_VIOLATION_NUMBER": (
        "Identifier",
        "Investigate",
        "19,986 unique non-null values but 78.87% missing",
        "Investigate missingness and identifier usefulness"
    )
}

for col, values in decisions.items():
    feature_decisions.loc[
        feature_decisions["Column"] == col,
        ["Role", "Decision", "Reason", "Preprocessing"]
    ] = values

feature_decisions

,Column,Role,Decision,Reason,Preprocessing
0,ISN_DOB_BIS_EXTRACT,Identifier,Remove,Unique value for every record; no predictive m...,Drop
1,ECB_VIOLATION_NUMBER,Identifier,Remove,Unique violation identifier for every record,Drop
2,ECB_VIOLATION_STATUS,Potential leakage,Investigate,Status may change as the violation progresses,Categorical encoding if retained
3,DOB_VIOLATION_NUMBER,Identifier,Investigate,"19,986 unique non-null values but 78.87% missing",Investigate missingness and identifier usefulness
4,BIN,Feature,Investigate/Keep,Building identifier; repeated buildings allow ...,Historical feature engineering / categorical h...
5,BORO,Feature,Investigate/Keep,Geographical information with 5 categories,Categorical encoding
6,BLOCK,Feature,Investigate/Keep,Location identifier,Categorical/location handling
7,LOT,Feature,Investigate/Keep,Location identifier,Categorical/location handling
8,HEARING_DATE,Potential leakage,Investigate,Hearing occurs later in the violation process,Datetime conversion only if legitimately avail...
9,HEARING_TIME,,,,
10,SERVED_DATE,,,,
11,ISSUE_DATE,Feature,Keep,Available at the issue stage and contains temp...,Datetime conversion + feature engineering
12,SEVERITY,Target,Target,Three-class prediction target,Encode target
13,VIOLATION_TYPE,Feature,Investigate/Keep,12 violation categories may contain predictive...,Categorical encoding
14,RESPONDENT_NAME,,,,
15,RESPONDENT_HOUSE_NUMBER,,,,
16,RESPONDENT_STREET,,,,
17,RESPONDENT_CITY,,,,
18,RESPONDENT_ZIP,,,,
19,VIOLATION_DESCRIPTION,,,,
20,PENALITY_IMPOSED,Feature,Investigate,Monetary variable stored as formatted text; pr...,String-to-numeric conversion if retained
21,AMOUNT_PAID,Potential leakage,Investigate,Payment may occur after the prediction point,String-to-numeric if retained
22,BALANCE_DUE,Potential leakage,Investigate,Financial status may be generated after the pr...,String-to-numeric + investigate negative values
23,INFRACTION_CODE1,,,,
24,SECTION_LAW_DESCRIPTION1,,,,
25,INFRACTION_CODE2,,,,
26,SECTION_LAW_DESCRIPTION2,,,,
27,INFRACTION_CODE3,,,,
28,SECTION_LAW_DESCRIPTION3,,,,
29,INFRACTION_CODE4,,,,
30,SECTION_LAW_DESCRIPTION4,,,,
31,INFRACTION_CODE5,,,,
32,SECTION_LAW_DESCRIPTION5,,,,
33,INFRACTION_CODE6,,,,
34,SECTION_LAW_DESCRIPTION6,,,,
35,INFRACTION_CODE7,,,,
36,SECTION_LAW_DESCRIPTION7,,,,
37,INFRACTION_CODE8,,,,
38,SECTION_LAW_DESCRIPTION8,,,,
39,INFRACTION_CODE9,,,,
40,SECTION_LAW_DESCRIPTION9,,,,
41,INFRACTION_CODE10,,,,
42,SECTION_LAW_DESCRIPTION10,,,,
43,AGGRAVATED_LEVEL,Feature,Investigate,Strong relationship with SEVERITY; need to con...,Categorical encoding if retained
44,HEARING_STATUS,Potential leakage,Investigate,Status may be determined after the initial vio...,Categorical encoding if retained
45,CERTIFICATION_STATUS,Potential leakage,Investigate,May represent a later stage of the violation p...,Categorical encoding if retained

In [19]:
respondent_columns = [
    "RESPONDENT_NAME",
    "RESPONDENT_HOUSE_NUMBER",
    "RESPONDENT_STREET",
    "RESPONDENT_CITY",
    "RESPONDENT_ZIP"
]

for col in respondent_columns:
    print("\n" + "=" * 60)
    print(col)
    print("Data type:", df[col].dtype)
    print("Missing:", df[col].isna().sum())
    print("Missing %:", round(df[col].isna().mean() * 100, 2))
    print("Unique:", df[col].nunique())

    print("\nTop 10 values:")
    print(df[col].value_counts(dropna=False).head(10))

============================================================
RESPONDENT_NAME
Data type: str
Missing: 75
Missing %: 0.07
Unique: 36932

Top 10 values:
RESPONDENT_NAME
DEPARTMENT OF EDUCATION      4264
DEPT OF EDUCATION            2869
DEPARTMENT OF EDUCATION 0     286
ON STAR MANAGEMENT LLC        235
INNOVATIVE CONSTR NYC LLC     227
L&L CONSTRUCTION DEVELOP      210
MOD CONSULTANTS LLC           197
YAFE MEOD CORP                167
NYC HOUSING AUTHORITY         161
MJH CONSTRUCTION CORP         158
Name: count, dtype: int64

============================================================
RESPONDENT_HOUSE_NUMBER
Data type: str
Missing: 22754
Missing %: 22.21
Unique: 8702

Top 10 values:
RESPONDENT_HOUSE_NUMBER
NaN       22754
172-14      692
670         555
199         434
4118        423
40          395
1           382
130         346
253         313
250         262
Name: count, dtype: int64

============================================================
RESPONDENT_STREET
Data type: str
Missing: 7784
Missing %: 7.6
Unique: 10036

Top 10 values:
RESPONDENT_STREET
NaN               7784
BROADWAY          1998
LEE AVENUE         735
5 AVENUE           733
89 AVENUE          726
MYRTLE AVENUE      713
PARK AVENUE        650
3 AVENUE           634
14 AVENUE          631
MADISON AVENUE     584
Name: count, dtype: int64

============================================================
RESPONDENT_CITY
Data type: str
Missing: 8279
Missing %: 8.08
Unique: 1312

Top 10 values:
RESPONDENT_CITY
BROOKLYN         29745
NEW YORK         13702
NaN               8279
BRONX             8076
JAMAICA           4070
FLUSHING          3973
STATEN ISLAND     3857
MANHATTAN         3236
QUEENS            1865
GREAT NECK        1426
Name: count, dtype: int64

============================================================
RESPONDENT_ZIP
Data type: str
Missing: 8932
Missing %: 8.72
Unique: 1411

Top 10 values:
RESPONDENT_ZIP
NaN      8932
11219    2679
11211    2104
11205    1715
11230    1611
11204    1449
10001    1423
11354    1411
11218    1365
11432    1259
Name: count, dtype: int64

In [20]:
print("=" * 60)
print("VIOLATION_DESCRIPTION")

print("Data type:", df["VIOLATION_DESCRIPTION"].dtype)
print("Missing:", df["VIOLATION_DESCRIPTION"].isna().sum())
print("Missing %:", round(df["VIOLATION_DESCRIPTION"].isna().mean() * 100, 2))
print("Unique:", df["VIOLATION_DESCRIPTION"].nunique())

print("\nTop 20 descriptions:")
print(df["VIOLATION_DESCRIPTION"].value_counts(dropna=False).head(20))

============================================================
VIOLATION_DESCRIPTION
Data type: str
Missing: 8
Missing %: 0.01
Unique: 97978

Top 20 descriptions:
VIOLATION_DESCRIPTION
1RCNY 103-09(E). FAILURE TO FILE A RETAINING WALL CONDITION ASSESSMENTREPORT BY THE DEADLINE AS REQUIRED BY 1RCNY 103-09(E)(2) AND (5). TO DATE, THE DEPARTMENT HAS NOT RECIEVED A RETAINING WALL CONDITION ASSESS    368
1RCNY 103-09(E). FAILURE TO FILE A RETAINING WALL CONDITION ASSESSMENTREPORT BY THE DEADLINE AS REQUIRED BY 1RCNY 103-09(E)(2) AND (5). TO DATE, THE DEPARTMENT HAS NOT RECEIVED A RETAINING WALL CONDITION ASSESS    332
NO EN DRAWING APPROVED FROM DOB PROVIDED ON THE JOB SITE AT THE TIME OF INSPECTION., MAINTAIN/DISPLAY REQUIRED DOCUMENTS; PLEASE GO TO HTTPS://WWW1.NYC.GOV/SITE/BUILDINGS/CODES/ENERGY-CONSERVATION-CODE.PAGE AND     78
RTS CLASS 1: FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER. SERVICE ELEVATOR EQUIPMENT AS PER BC3001.2 & 27-987. UPON INSPECTION, THE DEVICE IS FOUND TO BE OUT OF SERVICE, CREATING A HAZARDOUS CONDITION     74
FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER. SERVICE ELEVATOR EQUIPMENT AS PER BC3001.2 & 27-987. UPON INSPECTION, THE ONLY DEVICE IN THE SECTION OF THE BUILDING IS FOUND TO BE OUT OF SERVICE, CREATIN     55
FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER. UPON INSPECTION, THE DEVICE IS FOUND TO BE OUT OF SERVICE. REMEDY: RESTORE TO SERVICE AND CONTACT THE DOB ELEVATOR DIVISION AT ELEVATORIR@BUILDINGS.NYC.GOV     54
THE ONLY ELEVATOR IN BUILDING (OR SECTION OF BUILDING) OUT OF SERVICE. UPON INSPECTION, THE DEVICE IS FOUND TO BE OUT-OF-SERVICE CREATING A HAZARDOUS CONDITION AS PER 1RCNY 11-02. REMEDY: RESTORE TO SERVICE IMM     51
CLASS 1 RTS: FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER. SERVICE ELEVATOR EQUIPMENT AS PER BC3001.2 & 27-987. UPON INSPECTION, THE DEVICE IS FOUND TO BE OUT OF SERVICE, CREATING A HAZARDOUS CONDITION     48
CEASE USE ITEM: DOOR ZONE RESTRICTOR INOPERATIVE. THIS IS A SAFETY FEATURE WHICH ENSURES PASSENGER SAFETY. REMEDY: TO RESTORE SERVICE, EMAIL THE D.O.B. EIR@BUILDINGS.NYC.GOV. ELEVATOR DIVISION AT FOR A REINSPEC     47
FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER. SERVICE ELEVATOR EQUIPMENT AS PER BC3001.2 & 27-987. UPON INSPECTION, THE DEVICE IS FOUND TO BE OUT OF SERVICE, CREATING A HAZARDOUS CONDITION PER 1RCNY 11     45
CLASS 1 CEASE USE ITEM: DOOR ZONE RESTRICTOR INOPERATIVE. THIS IS A SAFETY FEATURE WHICH ENSURES PASSENGER SAFETY. REMEDY: TO RESTORE SERVICE, EMAIL THE D.O.B. EIR@BUILDINGS.NYC.GOV. FOR A REINSPECTION. CLASS 2     43
REPAIR AND RESTORE TO SERVICE.                                                                                                                                                                                         42
AN ELEVATOR IN SECTION OF BUILDING OR BUILDING IS OUT-OF-SERVICE. UPON INSPECTION THE DEVICE IS FOUND TO BE OUT-OF-SERVICE CREATING A HAZARDOUS CONDITION AS PER 1RCNY 11-02. RESTORE TO SERVICE IMMEDIATELY AND N     41
CLASS1 ITEM: RTS FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER, SERVICE ELEVATOR EQUIPMENT AS PER CODE BC3001.2 & 27-987. UPON INSPECTION, THE DEVICE IS FOUND TO BE OUT OF SERVICE, CREATING A HAZARDOUS      32
AT TIME OF INSPECTION IN RESPONSE TO COMPLAINT I OBSERVED UNDERSIDE OF SIDEWALK SHED A NOT ILLUMINATED AS PER 3307.6.4.8. THIS CREATES A HAZARDOUS CONDITION FOR PUBLIC WALKING UNDERNEATH WHILE DARK AND NOT BEIN     29
CEASE USE ITEM: DOOR ZONE RESTRICTOR INOPERATIVE, CREATING A HAZARDOUS CONDITION PER 1RCNY11-02. REMEDY: RESTORE TO SERVICE IMMEDIATLEY AND E-MAIL THE ELEVATOR DIVISION AT EIR@BUILDINGS.NYC.GOV FOR A RE-INSPECT     28
: FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER. SERVICE ELEVATOR EQUIPMENT AS PER BC3001.2 & 27-987. UPON INSPECTION, THE DEVICE IS FOUND TO BE OUT OF SERVICE, CREATING A HAZARDOUS CONDITION PER 1RCNY      26
CLASS 1 ITEM: FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER. SERVICE ELEVATOR EQUIPMENT AS PER BC3001.2 & 27-987. UPON INSPECTION, THE DEVICE IS FOUND TO BE OUT OF SERVICE, CREATING A HAZARDOUS CONDITIO     26
OCCUPANCY CONTRARY TO THAT ALLOWED BY C OF O AND/OR DEPARTMENT OF BUILDING RECORDS. PRIVATE DWELLING ILLEGALLY CONVERTED INTO MULTIPLE DWELLING. PARTITIONS ERECTED CREATING AN ILLEGAL CLASS "A" APARTMENT AT CEL     25
RESTORE SERVICE TO DEVICE.                                                                                                                                                                                             25
Name: count, dtype: int64

In [21]:
infraction_columns = [
    "INFRACTION_CODE1",
    "INFRACTION_CODE2",
    "INFRACTION_CODE3",
    "INFRACTION_CODE4",
    "INFRACTION_CODE5",
    "INFRACTION_CODE6",
    "INFRACTION_CODE7",
    "INFRACTION_CODE8",
    "INFRACTION_CODE9",
    "INFRACTION_CODE10"
]

for col in infraction_columns:
    print("\n" + "=" * 60)
    print(col)
    print("Data type:", df[col].dtype)
    print("Missing:", df[col].isna().sum())
    print("Missing %:", round(df[col].isna().mean() * 100, 2))
    print("Unique:", df[col].nunique(dropna=True))
    print("Top values:")
    print(df[col].value_counts(dropna=False).head(10))

============================================================
INFRACTION_CODE1
Data type: str
Missing: 0
Missing %: 0.0
Unique: 326
Top values:
INFRACTION_CODE1
202    8645
263    7642
101    6412
102    6077
201    5894
2P7    3779
151    3598
251    3391
187    2526
223    2028
Name: count, dtype: int64

============================================================
INFRACTION_CODE2
Data type: str
Missing: 99864
Missing %: 97.46
Unique: 128
Top values:
INFRACTION_CODE2
NaN         99864
172           433
127           369
2P7           246
102           158
1P7           145
101           139
182           114
1.00E+06       94
151            66
Name: count, dtype: int64

============================================================
INFRACTION_CODE3
Data type: float64
Missing: 102447
Missing %: 99.98
Unique: 2
Top values:
INFRACTION_CODE3
NaN            102447
100000000.0        19
176.0               1
Name: count, dtype: int64

============================================================
INFRACTION_CODE4
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
INFRACTION_CODE4
NaN    102467
Name: count, dtype: int64

============================================================
INFRACTION_CODE5
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
INFRACTION_CODE5
NaN    102467
Name: count, dtype: int64

============================================================
INFRACTION_CODE6
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
INFRACTION_CODE6
NaN    102467
Name: count, dtype: int64

============================================================
INFRACTION_CODE7
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
INFRACTION_CODE7
NaN    102467
Name: count, dtype: int64

============================================================
INFRACTION_CODE8
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
INFRACTION_CODE8
NaN    102467
Name: count, dtype: int64

============================================================
INFRACTION_CODE9
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
INFRACTION_CODE9
NaN    102467
Name: count, dtype: int64

============================================================
INFRACTION_CODE10
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
INFRACTION_CODE10
NaN    102467
Name: count, dtype: int64

In [22]:
law_columns = [
    "SECTION_LAW_DESCRIPTION1",
    "SECTION_LAW_DESCRIPTION2",
    "SECTION_LAW_DESCRIPTION3",
    "SECTION_LAW_DESCRIPTION4",
    "SECTION_LAW_DESCRIPTION5",
    "SECTION_LAW_DESCRIPTION6",
    "SECTION_LAW_DESCRIPTION7",
    "SECTION_LAW_DESCRIPTION8",
    "SECTION_LAW_DESCRIPTION9",
    "SECTION_LAW_DESCRIPTION10"
]

for col in law_columns:
    print("\n" + "=" * 60)
    print(col)
    print("Data type:", df[col].dtype)
    print("Missing:", df[col].isna().sum())
    print("Missing %:", round(df[col].isna().mean() * 100, 2))
    print("Unique:", df[col].nunique(dropna=True))
    print("Top values:")
    print(df[col].value_counts(dropna=False).head(10))

============================================================
SECTION_LAW_DESCRIPTION1
Data type: str
Missing: 7994
Missing %: 7.8
Unique: 225
Top values:
SECTION_LAW_DESCRIPTION1
28-301.1                                                                    FAILURE TO MAINTAIN BLDG IN CODE-COMPLIANT MANNER                         15690
28-105.1                                                                    WORK WITHOUT A PERMIT                                                     13033
NaN                                                                                                                                                    7994
AC 28-204.4                                                                 FAIL TO COMPLY W/COMMISSIONER ORDER TO FILE CERT OF CORRECTION W/DOB       7642
28-301.1                                                                    FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER: SERVICE EQUIPME     3598
28-301.1                                                                    FAILURE TO MAINTAIN BUILDING IN CODE-COMPLAINT MANNER:SERVICE EQUIPMEN     3391
28-118.3.2                                                                  OCC CONTRARY TO THAT ALLOWED BY THE C OF O OR DOB RECORDS                  3221
27-3018(B)                                                                  ELECTRICAL WORK WITHOUT A PERMIT                                           3207
27-/28-/BC-MISC                                                             MISCELLANEOUS VIOLATIONS                                                   2545
28-201.1                                                                    UNLAWFUL ACTS.  FAILURE TO COMPLY WITH AN ORDER OF THE COMMISSIONER        2526
Name: count, dtype: int64

============================================================
SECTION_LAW_DESCRIPTION2
Data type: str
Missing: 100342
Missing %: 97.93
Unique: 89
Top values:
SECTION_LAW_DESCRIPTION2
NaN                                                                                                                                                   100342
28-202.1                                                                    ADDITIONAL DAILY PENALTY FOR CLASS 1 VIOLATION OF 28-210.1 OR 28-210.2       433
27-369,BC 1020.2                                                            FAIL TO PROVIDE UNOBSTRUCTED EXIT PASSAGEWAY                                 369
28-301.1                                                                    FAILURE TO MAINTAIN BLDG IN CODE-COMPLIANT MANNER                            184
28-105.1                                                                    WORK WITHOUT A PERMIT                                                        172
28-105.12.2                                                                 WORK DOES NOT CONFORM TO APPROVED CONSTRUCTION DOCUMENTS AND/OR APPROV       114
28-202.1                                                                    ADDITIONAL DAILY PENALTY FOR CLASS 1 VIOLATION OF 28-210.3                    94
28-301.1                                                                    FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT MANNER: SERVICE EQUIPME        66
28-302.1                                                                    FAILURE TO MAINTAIN BLDG WALL(S) OR APPURTENANCES                             64
BC 3303.4 & 27-1018                                                         FAILURE TO MAINTAIN ADEQUATE HOUSEKEEPING PER SECTION REQUIREMENTS            63
Name: count, dtype: int64

============================================================
SECTION_LAW_DESCRIPTION3
Data type: str
Missing: 102447
Missing %: 99.98
Unique: 2
Top values:
SECTION_LAW_DESCRIPTION3
NaN                                                                                                                                                  102447
28-210.1                                                                    CONVERT/MAINTAIN/OCCUPY MULT DWELLING W/3 OR MORE UNITS THAN APPROVED        19
BC 3306.2.1                                                                 FAILURE TO PROVIDE SAFETY ZONE FOR DEMOLITION OPERATIONS.                     1
Name: count, dtype: int64

============================================================
SECTION_LAW_DESCRIPTION4
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
SECTION_LAW_DESCRIPTION4
NaN    102467
Name: count, dtype: int64

============================================================
SECTION_LAW_DESCRIPTION5
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
SECTION_LAW_DESCRIPTION5
NaN    102467
Name: count, dtype: int64

============================================================
SECTION_LAW_DESCRIPTION6
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
SECTION_LAW_DESCRIPTION6
NaN    102467
Name: count, dtype: int64

============================================================
SECTION_LAW_DESCRIPTION7
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
SECTION_LAW_DESCRIPTION7
NaN    102467
Name: count, dtype: int64

============================================================
SECTION_LAW_DESCRIPTION8
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
SECTION_LAW_DESCRIPTION8
NaN    102467
Name: count, dtype: int64

============================================================
SECTION_LAW_DESCRIPTION9
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
SECTION_LAW_DESCRIPTION9
NaN    102467
Name: count, dtype: int64

============================================================
SECTION_LAW_DESCRIPTION10
Data type: float64
Missing: 102467
Missing %: 100.0
Unique: 0
Top values:
SECTION_LAW_DESCRIPTION10
NaN    102467
Name: count, dtype: int64

In [23]:
target_words = [
    "CLASS 1",
    "CLASS1",
    "CLASS - 1",
    "CLASS 2",
    "CLASS2",
    "CLASS - 2",
    "CLASS 3",
    "CLASS3",
    "CLASS - 3"
]

description_text = (
    df["VIOLATION_DESCRIPTION"]
    .fillna("")
    .astype(str)
    .str.upper()
)

for word in target_words:
    count = description_text.str.contains(
        word,
        regex=False
    ).sum()

    if count > 0:
        print(f"{word}: {count}")

CLASS 1: 2470
CLASS1: 55
CLASS 2: 1954
CLASS2: 20
CLASS 3: 3

In [24]:
feature_decisions.loc[
    feature_decisions["Column"] == "VIOLATION_DESCRIPTION",
    ["Role", "Decision", "Reason", "Preprocessing"]
] = (
    "Potential leakage",
    "Remove",
    "Description explicitly contains severity class labels in thousands of records",
    "Drop to prevent target leakage"
)

feature_decisions.loc[
    feature_decisions["Column"] == "INFRACTION_CODE1",
    ["Role", "Decision", "Reason", "Preprocessing"]
] = (
    "Feature",
    "Keep",
    "326 categories and no missing values; represents violation-related code",
    "Categorical encoding"
)

feature_decisions.loc[
    feature_decisions["Column"] == "INFRACTION_CODE3",
    ["Role", "Decision", "Reason", "Preprocessing"]
] = (
    "Feature",
    "Remove",
    "99.98% missing",
    "Drop due to extreme missingness"
)

for col in [
    "INFRACTION_CODE4",
    "INFRACTION_CODE5",
    "INFRACTION_CODE6",
    "INFRACTION_CODE7",
    "INFRACTION_CODE8",
    "INFRACTION_CODE9",
    "INFRACTION_CODE10"
]:
    feature_decisions.loc[
        feature_decisions["Column"] == col,
        ["Role", "Decision", "Reason", "Preprocessing"]
    ] = (
        "Feature",
        "Remove",
        "100% missing",
        "Drop"
    )

In [25]:
pd.crosstab(
    df["AGGRAVATED_LEVEL"],
    df["SEVERITY"],
    margins=True
)

SEVERITY                    CLASS - 1  CLASS - 2  CLASS - 3     All
AGGRAVATED_LEVEL
AGGRAVATED OFFENSE LEVEL 1       3066       4206         51    7323
AGGRAVATED OFFENSE LEVEL 2        777        165          3     945
NO                              36830      53236       4133   94199
All                             40673      57607       4187  102467

In [26]:
pd.crosstab(
    df["AGGRAVATED_LEVEL"],
    df["SEVERITY"],
    normalize="index"
).round(3) * 100

SEVERITY                    CLASS - 1  CLASS - 2  CLASS - 3
AGGRAVATED_LEVEL
AGGRAVATED OFFENSE LEVEL 1       41.9       57.4        0.7
AGGRAVATED OFFENSE LEVEL 2       82.2       17.5        0.3
NO                               39.1       56.5        4.4

In [27]:
bin_counts = df["BIN"].value_counts()

print("Total unique BINs:", bin_counts.shape[0])

print("\nBuildings with only 1 violation:")
print((bin_counts == 1).sum())

print("\nBuildings with more than 1 violation:")
print((bin_counts > 1).sum())

print("\nBuildings with 5+ violations:")
print((bin_counts >= 5).sum())

print("\nBuildings with 10+ violations:")
print((bin_counts >= 10).sum())

print("\nMaximum violations for one building:")
print(bin_counts.max())

Total unique BINs: 38743

Buildings with only 1 violation:
18826

Buildings with more than 1 violation:
19917

Buildings with 5+ violations:
5603

Buildings with 10+ violations:
1332

Maximum violations for one building:
61

In [28]:
print("\nDistribution of violations per building:")
print(bin_counts.describe())

Distribution of violations per building:
count    38743.000000
mean         2.642335
std          2.955160
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         61.000000
Name: count, dtype: float64

In [29]:
feature_decisions.loc[
    feature_decisions["Column"] == "BIN",
    ["Role", "Decision", "Reason", "Preprocessing"]
] = (
    "Feature",
    "Keep",
    "19,917 buildings have multiple historical violations; building history can provide predictive information",
    "Create leakage-safe historical violation features"
)

In [30]:
# Find the BIN with the most violations
top_bin = df["BIN"].value_counts().idxmax()

print("Selected BIN:", top_bin)
print("Number of violations:", (df["BIN"] == top_bin).sum())

print(
    df.loc[
        df["BIN"] == top_bin,
        ["BIN", "ISSUE_DATE", "SEVERITY", "VIOLATION_TYPE"]
    ].sort_values("ISSUE_DATE")
)

Selected BIN: 3121398.0
Number of violations: 61
             BIN  ISSUE_DATE   SEVERITY VIOLATION_TYPE
4253   3121398.0    20251121  CLASS - 2   Construction
4811   3121398.0    20251121  CLASS - 2   Construction
8177   3121398.0    20251121  CLASS - 1   Construction
8240   3121398.0    20251121  CLASS - 2   Construction
30780  3121398.0    20251121  CLASS - 2   Construction
...          ...         ...        ...            ...
81370  3121398.0    20251219  CLASS - 2   Construction
50096  3121398.0    20251219  CLASS - 2   Construction
64407  3121398.0    20251219  CLASS - 2   Construction
80749  3121398.0    20251219  CLASS - 2   Construction
30731  3121398.0    20260513  CLASS - 1   Construction

[61 rows x 4 columns]

In [31]:
top_bin = df["BIN"].value_counts().idxmax()

bin_history = (
    df[df["BIN"] == top_bin]
    .groupby("ISSUE_DATE")
    .agg(
        violations_on_date=("SEVERITY", "size"),
        class_1=("SEVERITY", lambda x: (x == "CLASS - 1").sum()),
        class_2=("SEVERITY", lambda x: (x == "CLASS - 2").sum()),
        class_3=("SEVERITY", lambda x: (x == "CLASS - 3").sum())
    )
    .sort_index()
)

print("BIN:", top_bin)
print(bin_history)

BIN: 3121398.0
            violations_on_date  class_1  class_2  class_3
ISSUE_DATE
20251121                     5        1        4        0
20251211                    10        1        9        0
20251212                    10        0       10        0
20251215                    10        0       10        0
20251216                    12        0       12        0
20251219                    13        0       13        0
20260513                     1        1        0        0

In [32]:
test_bin = top_bin

test_df = (
    df[df["BIN"] == test_bin]
    [["BIN", "ISSUE_DATE", "SEVERITY"]]
    .copy()
)

test_df = test_df.sort_values("ISSUE_DATE")

date_counts = (
    test_df
    .groupby("ISSUE_DATE")
    .size()
    .sort_index()
)

previous_counts = date_counts.cumsum().shift(fill_value=0)

test_df["PREVIOUS_VIOLATION_COUNT"] = (
    test_df["ISSUE_DATE"].map(previous_counts)
)

print(
    test_df[
        ["BIN", "ISSUE_DATE", "SEVERITY",
         "PREVIOUS_VIOLATION_COUNT"]
    ].to_string(index=False)
)

      BIN  ISSUE_DATE  SEVERITY  PREVIOUS_VIOLATION_COUNT
3121398.0    20251121 CLASS - 2                         0
3121398.0    20251121 CLASS - 2                         0
3121398.0    20251121 CLASS - 1                         0
3121398.0    20251121 CLASS - 2                         0
3121398.0    20251121 CLASS - 2                         0
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 1                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20260513 CLASS - 1                        60

In [33]:
# Create previous violation count for every record

# Work on a temporary copy
history_df = df[["BIN", "ISSUE_DATE"]].copy()

# Keep original row order
history_df["_original_order"] = range(len(history_df))

# Sort by building and issue date
history_df = history_df.sort_values(
    ["BIN", "ISSUE_DATE", "_original_order"]
)

# Count violations for each BIN on each issue date
daily_counts = (
    history_df
    .groupby(["BIN", "ISSUE_DATE"], dropna=False)
    .size()
    .reset_index(name="VIOLATIONS_ON_DATE")
)

# Calculate previous violations for each BIN
daily_counts["PREVIOUS_VIOLATION_COUNT"] = (
    daily_counts
    .groupby("BIN", dropna=False)["VIOLATIONS_ON_DATE"]
    .cumsum()
    - daily_counts["VIOLATIONS_ON_DATE"]
)

# Merge the historical count back to the original dataset
df = df.merge(
    daily_counts[
        ["BIN", "ISSUE_DATE", "PREVIOUS_VIOLATION_COUNT"]
    ],
    on=["BIN", "ISSUE_DATE"],
    how="left"
)

# Buildings with missing BIN have no identifiable history
df.loc[df["BIN"].isna(), "PREVIOUS_VIOLATION_COUNT"] = 0

# Check the result
print("Rows:", len(df))
print(
    df["PREVIOUS_VIOLATION_COUNT"]
    .describe()
)

Rows: 102467
count    102467.000000
mean          1.669250
std           3.504407
min           0.000000
25%           0.000000
50%           0.000000
75%           2.000000
max          60.000000
Name: PREVIOUS_VIOLATION_COUNT, dtype: float64

In [34]:
print(
    df[
        df["BIN"] == 3121398
    ][
        ["BIN", "ISSUE_DATE", "SEVERITY",
         "PREVIOUS_VIOLATION_COUNT"]
    ]
    .sort_values("ISSUE_DATE")
    .to_string(index=False)
)

      BIN  ISSUE_DATE  SEVERITY  PREVIOUS_VIOLATION_COUNT
3121398.0    20251121 CLASS - 2                         0
3121398.0    20251121 CLASS - 2                         0
3121398.0    20251121 CLASS - 1                         0
3121398.0    20251121 CLASS - 2                         0
3121398.0    20251121 CLASS - 2                         0
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 1                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251211 CLASS - 2                         5
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251212 CLASS - 2                        15
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251215 CLASS - 2                        25
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251216 CLASS - 2                        35
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20251219 CLASS - 2                        47
3121398.0    20260513 CLASS - 1                        60

In [35]:
# Test previous severity counts for our selected BIN

test_history = (
    df[df["BIN"] == 3121398]
    [["BIN", "ISSUE_DATE", "SEVERITY"]]
    .copy()
)

# Count each severity class per BIN and issue date
daily_severity = (
    test_history
    .groupby(["BIN", "ISSUE_DATE", "SEVERITY"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

# Make sure all three classes exist as columns
for col in ["CLASS - 1", "CLASS - 2", "CLASS - 3"]:
    if col not in daily_severity.columns:
        daily_severity[col] = 0

# Rename columns
daily_severity = daily_severity.rename(columns={
    "CLASS - 1": "CLASS1_ON_DATE",
    "CLASS - 2": "CLASS2_ON_DATE",
    "CLASS - 3": "CLASS3_ON_DATE"
})

# Calculate previous counts
for col, new_col in [
    ("CLASS1_ON_DATE", "PREVIOUS_CLASS1_COUNT"),
    ("CLASS2_ON_DATE", "PREVIOUS_CLASS2_COUNT"),
    ("CLASS3_ON_DATE", "PREVIOUS_CLASS3_COUNT")
]:
    daily_severity[new_col] = (
        daily_severity
        .groupby("BIN")[col]
        .cumsum()
        - daily_severity[col]
    )

print(
    daily_severity[
        [
            "BIN",
            "ISSUE_DATE",
            "CLASS1_ON_DATE",
            "CLASS2_ON_DATE",
            "CLASS3_ON_DATE",
            "PREVIOUS_CLASS1_COUNT",
            "PREVIOUS_CLASS2_COUNT",
            "PREVIOUS_CLASS3_COUNT"
        ]
    ].to_string(index=False)
)

      BIN  ISSUE_DATE  CLASS1_ON_DATE  CLASS2_ON_DATE  CLASS3_ON_DATE  PREVIOUS_CLASS1_COUNT  PREVIOUS_CLASS2_COUNT  PREVIOUS_CLASS3_COUNT
3121398.0    20251121               1               4               0                      0                      0                      0
3121398.0    20251211               1               9               0                      1                      4                      0
3121398.0    20251212               0              10               0                      2                     13                      0
3121398.0    20251215               0              10               0                      2                     23                      0
3121398.0    20251216               0              12               0                      2                     33                      0
3121398.0    20251219               0              13               0                      2                     45                      0
3121398.0    20260513               1               0               0                      2                     58                      0

In [36]:
date_columns = [
    "ISSUE_DATE",
    "SERVED_DATE",
    "HEARING_DATE"
]

for col in date_columns:
    df[col + "_DT"] = pd.to_datetime(
        df[col].astype(str),
        format="%Y%m%d",
        errors="coerce"
    )

print(df[
    [
        "ISSUE_DATE",
        "ISSUE_DATE_DT",
        "SERVED_DATE",
        "SERVED_DATE_DT",
        "HEARING_DATE",
        "HEARING_DATE_DT"
    ]
].head())

   ISSUE_DATE ISSUE_DATE_DT  SERVED_DATE SERVED_DATE_DT  HEARING_DATE  \
0    20260601    2026-06-01     20260601     2026-06-01      20260821
1    20250805    2025-08-05     20250805     2025-08-05      20270415
2    20260624    2026-06-24     20260624     2026-06-24      20260902
3    20251203    2025-12-03     20251203     2025-12-03      20260908
4    20260722    2026-07-22     20260819     2026-08-19      20261030

  HEARING_DATE_DT
0      2026-08-21
1      2027-04-15
2      2026-09-02
3      2026-09-08
4      2026-10-30

In [37]:
# Validate converted date columns

dt_columns = [
    "ISSUE_DATE_DT",
    "SERVED_DATE_DT",
    "HEARING_DATE_DT"
]

for col in dt_columns:
    print("\n" + "=" * 50)
    print(col)
    print("Missing:", df[col].isna().sum())
    print("Minimum:", df[col].min())
    print("Maximum:", df[col].max())

print("\n" + "=" * 50)
print("CHRONOLOGICAL CHECKS")

print(
    "SERVED before ISSUE:",
    (df["SERVED_DATE_DT"] < df["ISSUE_DATE_DT"]).sum()
)

print(
    "HEARING before ISSUE:",
    (df["HEARING_DATE_DT"] < df["ISSUE_DATE_DT"]).sum()
)

print(
    "HEARING before SERVED:",
    (df["HEARING_DATE_DT"] < df["SERVED_DATE_DT"]).sum()
)

==================================================
ISSUE_DATE_DT
Missing: 0
Minimum: 2025-01-01 00:00:00
Maximum: 2026-09-10 00:00:00

==================================================
SERVED_DATE_DT
Missing: 7
Minimum: 2025-01-01 00:00:00
Maximum: 2026-09-10 00:00:00

==================================================
HEARING_DATE_DT
Missing: 0
Minimum: 2025-02-06 00:00:00
Maximum: 2027-12-22 00:00:00

==================================================
CHRONOLOGICAL CHECKS
SERVED before ISSUE: 0
HEARING before ISSUE: 0
HEARING before SERVED: 0

In [38]:
# Inspect records where SERVED_DATE was originally 0

missing_served = df[df["SERVED_DATE"] == 0]

print("Number of records:", len(missing_served))

print(
    missing_served[
        [
            "ECB_VIOLATION_NUMBER",
            "BIN",
            "ISSUE_DATE",
            "SERVED_DATE",
            "HEARING_DATE",
            "SEVERITY",
            "VIOLATION_TYPE",
            "ECB_VIOLATION_STATUS",
            "HEARING_STATUS"
        ]
    ].to_string(index=False)
)

Number of records: 7
ECB_VIOLATION_NUMBER       BIN  ISSUE_DATE  SERVED_DATE  HEARING_DATE  SEVERITY VIOLATION_TYPE ECB_VIOLATION_STATUS HEARING_STATUS
           39156479P 2055615.0    20250808            0      20260227 CLASS - 1      Elevators               ACTIVE   IN VIOLATION
           39149568L 3197976.0    20250602            0      20261008 CLASS - 1   Construction               ACTIVE        PENDING
           35483827P 2102335.0    20250216            0      20261113 CLASS - 1   Construction               ACTIVE        PENDING
           35482615Z 2077614.0    20250620            0      20261106 CLASS - 1   Construction               ACTIVE        PENDING
           39167302N 3399379.0    20251117            0      20260128 CLASS - 2   Construction               ACTIVE        DEFAULT
           35729351X 3025119.0    20260723            0      20261007 CLASS - 1   Construction               ACTIVE        PENDING
           35686012Y 3128689.0    20260319            0      20260527 CLASS - 1   Construction              RESOLVE   IN VIOLATION

In [39]:
prediction_audit = pd.DataFrame({
    "Column": df.columns,
    "Role": "",
    "Decision": "",
    "Reason": ""
})

prediction_audit.loc[prediction_audit["Column"] == "SEVERITY",
                     ["Role", "Decision", "Reason"]] = [
    "Target",
    "Keep",
    "Target variable to predict"
]

identifier_columns = [
    "ISN_DOB_BIS_EXTRACT",
    "ECB_VIOLATION_NUMBER",
    "DOB_VIOLATION_NUMBER"
]

for col in identifier_columns:
    prediction_audit.loc[prediction_audit["Column"] == col,
                         ["Role", "Decision", "Reason"]] = [
        "Identifier",
        "Investigate/Remove",
        "Identifier; not directly meaningful as a predictive feature"
    ]

potential_leakage = [
    "SERVED_DATE",
    "HEARING_DATE",
    "HEARING_TIME",
    "ECB_VIOLATION_STATUS",
    "AMOUNT_PAID",
    "BALANCE_DUE",
    "HEARING_STATUS",
    "CERTIFICATION_STATUS"
]

for col in potential_leakage:
    prediction_audit.loc[prediction_audit["Column"] == col,
                         ["Role", "Decision", "Reason"]] = [
        "Potential leakage",
        "Investigate",
        "May contain information generated after the violation was issued"
    ]

print(prediction_audit.to_string(index=False))

                   Column              Role           Decision                                                           Reason
      ISN_DOB_BIS_EXTRACT        Identifier Investigate/Remove      Identifier; not directly meaningful as a predictive feature
     ECB_VIOLATION_NUMBER        Identifier Investigate/Remove      Identifier; not directly meaningful as a predictive feature
     ECB_VIOLATION_STATUS Potential leakage        Investigate May contain information generated after the violation was issued
     DOB_VIOLATION_NUMBER        Identifier Investigate/Remove      Identifier; not directly meaningful as a predictive feature
                      BIN
                     BORO
                    BLOCK
                      LOT
             HEARING_DATE Potential leakage        Investigate May contain information generated after the violation was issued
             HEARING_TIME Potential leakage        Investigate May contain information generated after the violation was issued
              SERVED_DATE Potential leakage        Investigate May contain information generated after the violation was issued
               ISSUE_DATE
                 SEVERITY            Target               Keep                                       Target variable to predict
           VIOLATION_TYPE
          RESPONDENT_NAME
  RESPONDENT_HOUSE_NUMBER
        RESPONDENT_STREET
          RESPONDENT_CITY
           RESPONDENT_ZIP
    VIOLATION_DESCRIPTION
         PENALITY_IMPOSED
              AMOUNT_PAID Potential leakage        Investigate May contain information generated after the violation was issued
              BALANCE_DUE Potential leakage        Investigate May contain information generated after the violation was issued
         INFRACTION_CODE1
 SECTION_LAW_DESCRIPTION1
         INFRACTION_CODE2
 SECTION_LAW_DESCRIPTION2
         INFRACTION_CODE3
 SECTION_LAW_DESCRIPTION3
         INFRACTION_CODE4
 SECTION_LAW_DESCRIPTION4
         INFRACTION_CODE5
 SECTION_LAW_DESCRIPTION5
         INFRACTION_CODE6
 SECTION_LAW_DESCRIPTION6
         INFRACTION_CODE7
 SECTION_LAW_DESCRIPTION7
         INFRACTION_CODE8
 SECTION_LAW_DESCRIPTION8
         INFRACTION_CODE9
 SECTION_LAW_DESCRIPTION9
        INFRACTION_CODE10
SECTION_LAW_DESCRIPTION10
         AGGRAVATED_LEVEL
           HEARING_STATUS Potential leakage        Investigate May contain information generated after the violation was issued
     CERTIFICATION_STATUS Potential leakage        Investigate May contain information generated after the violation was issued
 PREVIOUS_VIOLATION_COUNT
            ISSUE_DATE_DT
           SERVED_DATE_DT
          HEARING_DATE_DT

In [40]:
# Show columns that have not yet been classified

unclassified = prediction_audit[
    prediction_audit["Role"] == ""
]["Column"].tolist()

print("Number of unclassified columns:", len(unclassified))

print("\nUnclassified columns:")
for i, col in enumerate(unclassified, start=1):
    print(f"{i:2}. {col}")

Number of unclassified columns: 38

Unclassified columns:
 1. BIN
 2. BORO
 3. BLOCK
 4. LOT
 5. ISSUE_DATE
 6. VIOLATION_TYPE
 7. RESPONDENT_NAME
 8. RESPONDENT_HOUSE_NUMBER
 9. RESPONDENT_STREET
10. RESPONDENT_CITY
11. RESPONDENT_ZIP
12. VIOLATION_DESCRIPTION
13. PENALITY_IMPOSED
14. INFRACTION_CODE1
15. SECTION_LAW_DESCRIPTION1
16. INFRACTION_CODE2
17. SECTION_LAW_DESCRIPTION2
18. INFRACTION_CODE3
19. SECTION_LAW_DESCRIPTION3
20. INFRACTION_CODE4
21. SECTION_LAW_DESCRIPTION4
22. INFRACTION_CODE5
23. SECTION_LAW_DESCRIPTION5
24. INFRACTION_CODE6
25. SECTION_LAW_DESCRIPTION6
26. INFRACTION_CODE7
27. SECTION_LAW_DESCRIPTION7
28. INFRACTION_CODE8
29. SECTION_LAW_DESCRIPTION8
30. INFRACTION_CODE9
31. SECTION_LAW_DESCRIPTION9
32. INFRACTION_CODE10
33. SECTION_LAW_DESCRIPTION10
34. AGGRAVATED_LEVEL
35. PREVIOUS_VIOLATION_COUNT
36. ISSUE_DATE_DT
37. SERVED_DATE_DT
38. HEARING_DATE_DT

In [41]:
basic_features = {
    "BIN": (
        "Feature",
        "Keep / Engineer",
        "Building identifier; useful for historical building-level features"
    ),
    
    "BORO": (
        "Feature",
        "Keep",
        "Geographical information available at issue stage"
    ),
    
    "BLOCK": (
        "Feature",
        "Keep / Engineer",
        "Location identifier; may provide geographical/building context"
    ),
    
    "LOT": (
        "Feature",
        "Keep / Engineer",
        "Location identifier; may provide building/location context"
    ),
    
    "ISSUE_DATE": (
        "Feature",
        "Keep / Engineer",
        "Available at prediction point; useful for temporal features"
    ),
    
    "VIOLATION_TYPE": (
        "Feature",
        "Keep",
        "Violation category available when violation is issued"
    ),
    
    "RESPONDENT_NAME": (
        "Administrative/Text",
        "Investigate",
        "High-cardinality field; direct encoding may not be appropriate"
    ),
    
    "RESPONDENT_HOUSE_NUMBER": (
        "Address",
        "Investigate",
        "Address information; usefulness requires investigation"
    ),
    
    "RESPONDENT_STREET": (
        "Address",
        "Investigate",
        "High-cardinality address field"
    ),
    
    "RESPONDENT_CITY": (
        "Address",
        "Investigate",
        "Geographical information; requires preprocessing"
    ),
    
    "RESPONDENT_ZIP": (
        "Feature",
        "Keep / Investigate",
        "Geographical information available at issue stage"
    ),
    
    "VIOLATION_DESCRIPTION": (
        "Text Feature",
        "Keep / Engineer",
        "Detailed description of the violation; potentially useful for severity prediction"
    )
}

for col, (role, decision, reason) in basic_features.items():
    prediction_audit.loc[
        prediction_audit["Column"] == col,
        ["Role", "Decision", "Reason"]
    ] = [role, decision, reason]

print(
    prediction_audit[
        prediction_audit["Column"].isin(basic_features.keys())
    ].to_string(index=False)
)

                 Column                Role           Decision                                                                            Reason
                    BIN             Feature    Keep / Engineer                Building identifier; useful for historical building-level features
                   BORO             Feature               Keep                                 Geographical information available at issue stage
                  BLOCK             Feature    Keep / Engineer                    Location identifier; may provide geographical/building context
                    LOT             Feature    Keep / Engineer                        Location identifier; may provide building/location context
             ISSUE_DATE             Feature    Keep / Engineer                       Available at prediction point; useful for temporal features
         VIOLATION_TYPE             Feature               Keep                             Violation category available when violation is issued
        RESPONDENT_NAME Administrative/Text        Investigate                    High-cardinality field; direct encoding may not be appropriate
RESPONDENT_HOUSE_NUMBER             Address        Investigate                            Address information; usefulness requires investigation
      RESPONDENT_STREET             Address        Investigate                                                    High-cardinality address field
        RESPONDENT_CITY             Address        Investigate                                  Geographical information; requires preprocessing
         RESPONDENT_ZIP             Feature Keep / Investigate                                 Geographical information available at issue stage
  VIOLATION_DESCRIPTION        Text Feature    Keep / Engineer Detailed description of the violation; potentially useful for severity prediction

In [42]:
# Classify infraction and legal-description columns

infraction_columns = [
    f"INFRACTION_CODE{i}" for i in range(1, 11)
]

law_description_columns = [
    f"SECTION_LAW_DESCRIPTION{i}" for i in range(1, 11)
]

for col in infraction_columns:
    prediction_audit.loc[
        prediction_audit["Column"] == col,
        ["Role", "Decision", "Reason"]
    ] = [
        "Feature",
        "Engineer / Investigate",
        "Infraction code may provide information about the violation; investigate missingness and usefulness"
    ]

for col in law_description_columns:
    prediction_audit.loc[
        prediction_audit["Column"] == col,
        ["Role", "Decision", "Reason"]
    ] = [
        "Text Feature",
        "Engineer / Investigate",
        "Legal description may provide information about the violation; investigate missingness and usefulness"
    ]

print(
    prediction_audit[
        prediction_audit["Column"].isin(
            infraction_columns + law_description_columns
        )
    ].to_string(index=False)
)

                   Column         Role               Decision                                                                                                Reason
         INFRACTION_CODE1      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
 SECTION_LAW_DESCRIPTION1 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness
         INFRACTION_CODE2      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
 SECTION_LAW_DESCRIPTION2 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness
         INFRACTION_CODE3      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
 SECTION_LAW_DESCRIPTION3 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness
         INFRACTION_CODE4      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
 SECTION_LAW_DESCRIPTION4 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness
         INFRACTION_CODE5      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
 SECTION_LAW_DESCRIPTION5 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness
         INFRACTION_CODE6      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
 SECTION_LAW_DESCRIPTION6 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness
         INFRACTION_CODE7      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
 SECTION_LAW_DESCRIPTION7 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness
         INFRACTION_CODE8      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
 SECTION_LAW_DESCRIPTION8 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness
         INFRACTION_CODE9      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
 SECTION_LAW_DESCRIPTION9 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness
        INFRACTION_CODE10      Feature Engineer / Investigate   Infraction code may provide information about the violation; investigate missingness and usefulness
SECTION_LAW_DESCRIPTION10 Text Feature Engineer / Investigate Legal description may provide information about the violation; investigate missingness and usefulness

In [43]:
# Temporary numeric conversion for investigation only

penalty_numeric = pd.to_numeric(
    df["PENALITY_IMPOSED"].astype(str).str.replace(",", "", regex=False),
    errors="coerce"
)

print("Missing after conversion:", penalty_numeric.isna().sum())
print("Minimum:", penalty_numeric.min())
print("Maximum:", penalty_numeric.max())

print("\nPenalty statistics by severity:")

print(
    pd.DataFrame({
        "PENALITY_IMPOSED": penalty_numeric,
        "SEVERITY": df["SEVERITY"]
    })
    .groupby("SEVERITY")["PENALITY_IMPOSED"]
    .describe()
)

Missing after conversion: 0
Minimum: 0
Maximum: 70000

Penalty statistics by severity:
             count         mean          std  min     25%     50%     75%  \
SEVERITY
CLASS - 1  40673.0  5817.252748  8083.207624  0.0  2500.0  2500.0  6250.0
CLASS - 2  57607.0  2085.626573  2158.654384  0.0   625.0  1250.0  2530.0
CLASS - 3   4187.0   295.013136   219.813653  0.0     0.0   280.0   500.0

               max
SEVERITY
CLASS - 1  70000.0
CLASS - 2  25000.0
CLASS - 3   2500.0

In [44]:
print("AGGRAVATED_LEVEL value counts:")
print(df["AGGRAVATED_LEVEL"].value_counts(dropna=False))

print("\nAGGRAVATED_LEVEL by VIOLATION_TYPE:")
print(
    pd.crosstab(
        df["VIOLATION_TYPE"],
        df["AGGRAVATED_LEVEL"],
        margins=True
    )
)

AGGRAVATED_LEVEL value counts:
AGGRAVATED_LEVEL
NO                            94199
AGGRAVATED OFFENSE LEVEL 1     7323
AGGRAVATED OFFENSE LEVEL 2      945
Name: count, dtype: int64

AGGRAVATED_LEVEL by VIOLATION_TYPE:
AGGRAVATED_LEVEL     AGGRAVATED OFFENSE LEVEL 1  AGGRAVATED OFFENSE LEVEL 2  \
VIOLATION_TYPE
Boilers                                      11                           3
Construction                               6367                         653
Cranes and Derricks                           0                           5
Elevators                                   396                         140
Local Law                                   266                          57
Plumbing                                      5                           0
Public Assembly                               1                           0
Quality of Life                              87                          43
Signs                                        31                           2
Site Safety                                   2                           3
Unknown                                     106                          38
Zoning                                       51                           1
All                                        7323                         945

AGGRAVATED_LEVEL        NO     All
VIOLATION_TYPE
Boilers               2261    2275
Construction         67635   74655
Cranes and Derricks    350     355
Elevators             6463    6999
Local Law              918    1241
Plumbing               275     280
Public Assembly         16      17
Quality of Life        787     917
Signs                  145     178
Site Safety            575     580
Unknown              13441   13585
Zoning                1333    1385
All                  94199  102467

In [45]:
# Compare aggravated level with issue and hearing dates

aggravated_dates = df[
    ["AGGRAVATED_LEVEL", "ISSUE_DATE_DT", "HEARING_DATE_DT"]
].copy()

print("AGGRAVATED LEVEL - ISSUE DATE")
print(
    aggravated_dates
    .groupby("AGGRAVATED_LEVEL")["ISSUE_DATE_DT"]
    .agg(["min", "max", "count"])
)

print("\nAGGRAVATED LEVEL - HEARING DATE")
print(
    aggravated_dates
    .groupby("AGGRAVATED_LEVEL")["HEARING_DATE_DT"]
    .agg(["min", "max", "count"])
)

AGGRAVATED LEVEL - ISSUE DATE
                                  min        max  count
AGGRAVATED_LEVEL
AGGRAVATED OFFENSE LEVEL 1 2025-01-02 2026-09-08   7323
AGGRAVATED OFFENSE LEVEL 2 2025-01-02 2026-09-02    945
NO                         2025-01-01 2026-09-10  94199

AGGRAVATED LEVEL - HEARING DATE
                                  min        max  count
AGGRAVATED_LEVEL
AGGRAVATED OFFENSE LEVEL 1 2025-03-18 2027-12-22   7323
AGGRAVATED OFFENSE LEVEL 2 2025-03-18 2027-06-10    945
NO                         2025-02-06 2027-10-15  94199

In [46]:
engineered_features = {
    "PREVIOUS_VIOLATION_COUNT": (
        "Historical Feature",
        "Keep",
        "Represents previous violations associated with the same building before the current record"
    ),
    
    "ISSUE_DATE_DT": (
        "Derived Temporal Feature",
        "Keep",
        "Converted version of ISSUE_DATE for temporal feature engineering"
    ),
    
    "SERVED_DATE_DT": (
        "Derived Temporal Feature",
        "Potential leakage",
        "Derived from SERVED_DATE, which may occur after the prediction point"
    ),
    
    "HEARING_DATE_DT": (
        "Derived Temporal Feature",
        "Potential leakage",
        "Derived from HEARING_DATE, which occurs later in the violation process"
    )
}

for col, (role, decision, reason) in engineered_features.items():
    if col in prediction_audit["Column"].values:
        prediction_audit.loc[
            prediction_audit["Column"] == col,
            ["Role", "Decision", "Reason"]
        ] = [role, decision, reason]

print(
    prediction_audit[
        prediction_audit["Column"].isin(engineered_features.keys())
    ].to_string(index=False)
)

                  Column                     Role          Decision                                                                                     Reason
PREVIOUS_VIOLATION_COUNT       Historical Feature              Keep Represents previous violations associated with the same building before the current record
           ISSUE_DATE_DT Derived Temporal Feature              Keep                           Converted version of ISSUE_DATE for temporal feature engineering
          SERVED_DATE_DT Derived Temporal Feature Potential leakage                       Derived from SERVED_DATE, which may occur after the prediction point
         HEARING_DATE_DT Derived Temporal Feature Potential leakage                     Derived from HEARING_DATE, which occurs later in the violation process

In [47]:
# Check whether previous violation count is valid
check = df[[
    "BIN",
    "ISSUE_DATE",
    "PREVIOUS_VIOLATION_COUNT"
]].copy()

# Convert issue date to datetime
check["ISSUE_DATE_DT"] = pd.to_datetime(
    check["ISSUE_DATE"].astype(str),
    format="%Y%m%d",
    errors="coerce"
)

print("Rows:", len(check))
print("Missing BIN:", check["BIN"].isna().sum())
print("Missing ISSUE_DATE:", check["ISSUE_DATE_DT"].isna().sum())
print("Missing previous count:", check["PREVIOUS_VIOLATION_COUNT"].isna().sum())

print("\nPrevious violation count statistics:")
print(check["PREVIOUS_VIOLATION_COUNT"].describe())

Rows: 102467
Missing BIN: 95
Missing ISSUE_DATE: 0
Missing previous count: 0

Previous violation count statistics:
count    102467.000000
mean          1.669250
std           3.504407
min           0.000000
25%           0.000000
50%           0.000000
75%           2.000000
max          60.000000
Name: PREVIOUS_VIOLATION_COUNT, dtype: float64

In [48]:
# Calculate the correct previous violation count
# using only violations from an EARLIER issue date.

temp = df[[
    "BIN",
    "ISSUE_DATE_DT",
    "PREVIOUS_VIOLATION_COUNT"
]].copy()

# Count violations for each building on each issue date
daily_counts = (
    temp.groupby(
        ["BIN", "ISSUE_DATE_DT"],
        dropna=False
    )
    .size()
    .reset_index(name="violations_on_date")
)

# Calculate cumulative violations BEFORE the current date
daily_counts["EXPECTED_PREVIOUS_COUNT"] = (
    daily_counts
    .groupby("BIN")["violations_on_date"]
    .cumsum()
    - daily_counts["violations_on_date"]
)

# Buildings with missing BIN cannot have reliable building history
daily_counts.loc[
    daily_counts["BIN"].isna(),
    "EXPECTED_PREVIOUS_COUNT"
] = 0

# Compare expected count with our existing feature
comparison = temp.merge(
    daily_counts[
        ["BIN", "ISSUE_DATE_DT", "EXPECTED_PREVIOUS_COUNT"]
    ],
    on=["BIN", "ISSUE_DATE_DT"],
    how="left"
)

# Find differences
comparison["difference"] = (
    comparison["PREVIOUS_VIOLATION_COUNT"]
    - comparison["EXPECTED_PREVIOUS_COUNT"]
)

print("Rows checked:", len(comparison))

print(
    "Rows where previous count differs:",
    (comparison["difference"] != 0).sum()
)

print(
    "Maximum difference:",
    comparison["difference"].abs().max()
)

Rows checked: 102467
Rows where previous count differs: 0
Maximum difference: 0.0